name: Test python

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  py:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt

    - name: tests
      run: |
        python -m unittest
